name: Rust

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt -- --check
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
    - name: Run tests
      run: cargo test
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
    - name: Run clippy
      run: cargo clippy
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@stable
    - name: Build documentation
      run: cargo doc --no-deps
    - uses: actions/upload-artifact@v7
      with:
        name: docs
        path: target/doc/
        if-no-files-found: error
